In [1]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [8]:
import numpy as np
arr=np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]])
print(arr)
print(arr.ndim)
type(arr)

[[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]]
3


numpy.ndarray

In [11]:
print(arr.shape)

(2, 2, 4)
