In [11]:
import numpy as np

## Reshape

In [9]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(3,2,2)

In [12]:
print(arr)
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


## Flattening [reshape(-1)]

In [14]:
thirdarr=newarr.reshape(-1)
print(thirdarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


## INdexing

In [15]:
arr=np.array([1,2,3,4,5])

In [16]:
print(arr[2])

3


In [21]:
arr=np.array([[1,2,3,4],[5,6,7,8],[1,2,3,4],[5,6,7,8]])

In [22]:
print(arr[1,3])

8


In [23]:
arr=np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]])

In [24]:
print(arr[0,1,1])

6


### bahar se andar jana hai

In [32]:
arr

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [34]:
arr[0,1,1] 

6

In [36]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])

for x in arr: print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [46]:
arr=arr.reshape(4,3)

In [47]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [48]:
for x in arr: print(x)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [53]:
for x in arr:
    for y in x:print(y)

[1 2 3]
[1 2 3]
[1 2 3]
[4 5 6]
[4 5 6]
[4 5 6]
[7 8 9]
[7 8 9]
[7 8 9]
[10 11 12]
[10 11 12]
[10 11 12]


## SLicing [start,end(length),step(1)]
#### end me last wala index is excluded

In [54]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [59]:
arr[2:5]

array([3, 4, 5])

In [73]:
arr[1::2]

array([ 2,  4,  6,  8, 10, 12])

In [76]:
arr=arr.reshape(3,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [80]:
arr[2,1:3]

array([10, 11])

## Search and Sort

In [110]:
arr=np.array([1,3,4,2,18,4,7,1,9,10,11,12])

In [103]:
n=np.where(arr==4)
n

(array([2, 5]),)

In [106]:
n=np.where(arr%2==0)
n

(array([ 1,  2,  3,  5,  7,  9, 11]),)

In [111]:
np.sort(arr)

array([ 1,  1,  2,  3,  4,  4,  7,  9, 10, 11, 12, 18])